### ISSUE TITLE
ObsidiPlates (?) breaks /help function in 1.7.10 BlastOff Pack

### ISSUE THREAD

**Issue by Prometheius** [Myrathi/ObsidiPlatesEx#8]
I don't know if ObsidiPlates is the sole cause of the following error.  To make sure I copied only the relevant info from the log I paused/saved the game right before and right after I tried the /? command.

[12:04:09] [Server thread/INFO]: Saving chunks for level 'Ezcore'/Nether
[12:04:45] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[12:04:49] [Server thread/ERROR]: Couldn't process command: '?'
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.ComparableTimSort.mergeHi(Unknown Source) ~[?:1.7.0_72]
    at java.util.ComparableTimSort.mergeAt(Unknown Source) ~[?:1.7.0_72]
    at java.util.ComparableTimSort.mergeForceCollapse(Unknown Source) ~[?:1.7.0_72]
    at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.7.0_72]
    at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.7.0_72]
    at java.util.Arrays.sort(Unknown Source) ~[?:1.7.0_72]
    at java.util.Collections.sort(Unknown Source) ~[?:1.7.0_72]
    at net.minecraft.command.CommandHelp.func_71534_d(SourceFile:84) ~[au.class:?]
    at net.minecraft.command.CommandHelp.func_71515_b(SourceFile:38) ~[au.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[12:04:49] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
[12:04:50] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu
[12:04:50] [Server thread/INFO]: Saving and pausing game...

**Comment by Myrathi** [comment]
Uh... `ObsidiPlates` doesn't show up in this log at all. The only mod I see is `inventorytweaks`. That and the fact ObP doesn't touch command processing in the slightest. Sorry.
